### ISSUE TITLE
object ‘survivalcoxr’ is not exported by 'namespace:survClip'

### ISSUE THREAD

**Issue by xuzhougeng** [cavei/MOSClip#1]
I try to install your packages with `devtools::install_github("cavei/MOSClip")`  in R 3.5.1 in CentOS 7.0 .

But  I got a error message as follow

```r
No methods found in package ‘GenomicRanges’ for request: ‘c’ when loading ‘qpgraph’
Error : object ‘survivalcoxr’ is not exported by 'namespace:survClip'
ERROR: lazy loading failed for package ‘MOSClip’
* removing ‘/home/xzg/R/x86_64-pc-linux-gnu-library/3.5/MOSClip’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpxyreFR/file220d83288725f/MOSClip_0.4.1.tar.gz’ had non-zero exit status
```

It told me that survClip didn't have the survivalcoxr function . When I google survClip, I find that  Package ‘survClip’ was removed from the CRAN repository. The last version of `survClip` is 0.2.3.

 Could you help me to solve this problem?

**Comment by cavei** [comment]
Hi,
thanks for your interest in MOSClip.

You are right, survClip is no longer available through CRAN but you can find it in github (https://github.com/cavei/survClip)

I fixed the problem.
Please run
devtools::install_github("cavei/survClip")

and then try installing MOSClip again.

Thanks

**Comment by MartinChiaHsinLiu** [comment]
Hi,
I install the MOSClip as the discussion.
It can be installed but some warnings happened when I library MOSClip.
Does it affect the usage of MOSClip?
It looks like some methods in GenomicRanges missing......

Thank you very much

```
* installing *source* package ‘MOSClip’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
No methods found in package ‘GenomicRanges’ for request: ‘c’ when loading ‘qpgraph’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
No methods found in package ‘GenomicRanges’ for request: ‘c’ when loading ‘qpgraph’
** testing if installed package can be loaded from final location
No methods found in package ‘GenomicRanges’ for request: ‘c’ when loading ‘qpgraph’
** testing if installed package keeps a record of temporary installation path
* DONE (MOSClip)
> library(MOSClip)
No methods found in package ‘GenomicRanges’ for request: ‘c’ when loading ‘qpgraph’
> 
```

**Comment by cavei** [comment]
Hi,
the warning refers to method not found upon "qpgraph" loading. MOSClip depends on qpgraph and load it so that why warning pop up. I've used MOSClip recently and this warning does not seems to affect its functionality!

Thanks
