### ISSUE TITLE
Questions about PCA

### ISSUE THREAD

**Issue by Jearbob** [cavei/MOSClip#6]
Hi,
We are very interested in MOSClip， but we can't understand how to get the result of PCA when performing KM-plotter. That means, how could I get the PCA results in form of exact gene names?
Thank you~

**Comment by cavei** [comment]
Dear Jearbob,
thank you for your interest.
If I understand correctly, you are looking for the PCA values.

For clarity I'll refer to the MOSClip tutorials.

In the module analysis, you can find the PCA values in 
multiOmicsReactome[["Activation of Matrix Metalloproteinases"]]@coxObjs[[1]] column expPC1
or in the modeuleView
multiOmicsReactome[["Activation of Matrix Metalloproteinases"]]@modulesView[[1]][[1]]$x (where '1' stay for first module, and the second '1' stay for the first omics.

For the pathway analysis it's very similar.
multiOmicsFullHuge[["VEGFA-VEGFR2 Pathway"]]@coxObj columns expPC1, expPC2, expPC3 for example.
and in multiOmicsFullHuge[["VEGFA-VEGFR2 Pathway"]]@pathView[[1]]$x
you'll find expression PCA

Cheers

**Comment by Jearbob** [comment]
Thanks for your sincere answer! It helps a lot. Best wishes!
